name: 'Update Homebrew Formula'
description: 'Generate and validate Homebrew formula for a release version'
inputs:
  version:
    description: 'New version to update to'
    required: true
  gh_token:
    description: 'GitHub token for gh API operations'
    required: true
  formula_path:
    description: 'Path to the formula file'
    required: false
    default: 'Formula/aikit.rb'
  formula_name:
    description: 'Name of the formula'
    required: false
    default: 'aikit'
  repo_path:
    description: 'Path where homebrew repo is checked out'
    required: false
    default: 'homebrew-cli'
runs:
  using: 'composite'
  steps:
    - name: Generate Homebrew formula
      shell: bash
      run: |
        HOMEBREW_REPO="${{ inputs.repo_path }}"

        if [ ! -d "$HOMEBREW_REPO" ]; then
          echo "❌ $HOMEBREW_REPO repository not checked out"
          exit 1
        fi

        cd "$HOMEBREW_REPO"
        chmod +x generate_formula.sh
        ./generate_formula.sh --version "${{ inputs.version }}"
      env:
        GH_TOKEN: ${{ inputs.gh_token }}

    - name: Validate generated Homebrew formula
      shell: bash
      run: |
        HOMEBREW_REPO="${{ inputs.repo_path }}"
        FORMULA_PATH="${{ inputs.formula_path }}"
        VERSION="${{ inputs.version }}"

        cd "$HOMEBREW_REPO"

        [ -f "$FORMULA_PATH" ] || { echo "❌ Formula file missing: $FORMULA_PATH"; exit 1; }
        grep -q "version \"$VERSION\"" "$FORMULA_PATH" || { echo "❌ Formula version mismatch: expected $VERSION"; exit 1; }

        grep -q 'aikit-aarch64-apple-darwin.tar.gz' "$FORMULA_PATH" || { echo "❌ Missing macOS arm64 URL"; exit 1; }
        grep -q 'aikit-x86_64-apple-darwin.tar.gz' "$FORMULA_PATH" || { echo "❌ Missing macOS x86_64 URL"; exit 1; }
        grep -q 'aikit-x86_64-unknown-linux-gnu.tar.gz' "$FORMULA_PATH" || { echo "❌ Missing Linux GNU URL"; exit 1; }
        grep -q 'aikit-x86_64-unknown-linux-musl.tar.gz' "$FORMULA_PATH" || { echo "❌ Missing Linux MUSL URL"; exit 1; }

        echo "✅ Homebrew formula validated for version $VERSION"
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
